# Generated by Django 3.2.9 on 2022-03-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='description',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='number',
            new_name='phone',
        ),
    ]
