# Generated by Django 3.2.9 on 2022-03-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220325_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='adress',
            new_name='address',
        ),
    ]
